### ISSUE TITLE
Since yesterday not working anymore?

### ISSUE THREAD

**Issue by maurodegroeve** [saman/notion-quote#5]
Since yesterday it is not displaying any quotes anymore.

**Comment by Karumji** [comment]
it's not working anymore

**Comment by jordanewert** [comment]
Same, I was just about to comment as well. I LOVE using this random quotes inside of Notion and as of yesterday or the day before, it hasn't been working.

**Comment by saman** [comment]
Yesterday I have updated to code to improve the sizing and add the shuffle button. 

I have test it in notion and the browser, both are working properly. 

Would you please add it again to your board maybe the problem get solved?

![image](https://user-images.githubusercontent.com/1576246/189417045-887c8646-da50-4b78-be43-fc8d01512f7a.jpeg)

**Comment by maurodegroeve** [comment]
Hello, 
Readding doesn't help it too. Even on the site I have just this white space with a grey stripe:
![image](https://user-images.githubusercontent.com/82209017/189420423-4de95f1f-0c26-4010-baa6-9920ece14472.png)

Is the code maybe changed? Or a new link?

**Comment by maurodegroeve** [comment]
Even the link in the README as example: https://saman.dev/notion-quote/?f=https://gist.githubusercontent.com/saman/a4326228c01f7fe15de6707655352300/raw/6ae8c92baae70fb842ddf91f3465ccab5f7b1622/my-notion-quote.json doesn't show anything for me.

**Comment by maurodegroeve** [comment]
Some extra context of how I used it:

1. I have my quotes in this format in a JSON file hosted using Gifthub Gist.

```
[
  {
    "author": "First Author Name",
    "content": "First Quote Content."
  },
  {
    "author": "Second Author Name",
    "content": "Second Quote Content."
  }
]
```

2. I go to the raw code of my gist and copy everything in the url after the usual https://gist.githubusercontent.com/[username]/

3. Then I paste that right after this link: https://saman.dev/notion-quote/?f=https://gist.githubusercontent.com/[username]/

4. That always worked for me, don’t know if I am doing something wrong?

**Comment by jmcolley** [comment]
Yeah, it doesn't seem to work with custom JSON files anymore. The example in the description doesn't even work.

**Comment by saman** [comment]
Thanks a lot for your feedback. My bad; while refactoring the code, the part of custom JSON had a problem. Now it should be fixed.

**Comment by maurodegroeve** [comment]
Yes, it's working again! Thanks for the help and for the tool!

**Comment by jordanewert** [comment]
Thank you!

-Jordan Ewert
(313) 986-1752
jordanewert.com

**Comment by jordanewert** [comment]
I tested again, and unfortunately, it's not working for me. I like the idea
of a shuffle button. I'm using Chrome 105 on Mac.

-Jordan Ewert
(313) 986-1752
jordanewert.com

**Comment by saman** [comment]
Hi @jordanewert, do you still face any issues? I tested again and everything seems fine.
