### ISSUE TITLE
Embed link not working

### ISSUE THREAD

**Issue by dharrison4** [saman/notion-quote#6]
404 not found, by clicking on the link in readme.md that points to https://www.notion.so/Embeds-6b7133323590447b9d8e963c136ebce5#5d54f8a0f7a44547b94d023bc09c2c55

Judging by the URL, this is potentially a public page that you have since changed, breaking the public URL.

I tried to use the wayback machine to see what the page might have, but no luck.

**Comment by saman** [comment]
Hii, thanks for sharing this.
That was on notion website, telling users what's an embed object.

I updated the readme now, the page is:
https://www.notion.so/help/embed-and-connect-other-apps
